### ISSUE TITLE
【バグ修正】プロセス死なないように改修

### ISSUE THREAD

**Issue by toru1055** [toru1055/oml-server#7]
- 修正内容
  - エラーハンドルをする。プロセス死なないように。
- エラーログ

```
TrainBatchService was started...
modelId: 4, labelMode: score
PredictBatchService was started...
java.lang.ArrayIndexOutOfBoundsException: 1
    at jp.thotta.oml.server.ml.BaseBinaryClassifier.read(BaseBinaryClassifier.java:47)
    at jp.thotta.oml.server.ml.LearnerFactory.readLearner(LearnerFactory.java:64)
    at jp.thotta.oml.server.service.BatchService.run(BatchService.java:35)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
TrainBatchService was end.
PredictBatchService was started...
```

**Comment by toru1055** [comment]
#### 原因
- たぶん原因は2プロセスで同時にファイルアクセスしたから。
- たぶんtrainしてすぐpredictする処理で、trainプロセスがファイルを保存している時にpredictがファイルreadするから起こる

#### 対策
- 本来はtrain/predictの処理をプロセスで分けるのではなくて、スレッドで分けるべき？
  - スレッドで分けていれば、同期を取れるはず
- とりあえずこのエラーが発生したときにプロセスが死ぬのはやばいので、例外処理をする
  - 同様のエラーが出た時はリトライする
  - [s.length==0ならリトライとか](https://github.com/toru1055/oml-server/blob/master/src/main/java/jp/thotta/oml/server/ml/BaseBinaryClassifier.java#L46)
